#ifndef ALGORITHMSGROUPPROJECTLU_ERRORS_H
#define ALGORITHMSGROUPPROJECTLU_ERRORS_H

#include <map>
#include <iostream>

// Коди помилок
static const int MATRIX_IS_NOT_SQUARE_ERROR_CODE = 1;

static const int CANNOT_DIVIDE_BY_ZERO_ERROR_CODE = 2;

static const int CANNOT_ADD_OR_SUBTRACT_ERROR_CODE = 3;

static const int CANNOT_MULTIPLY_ERROR_CODE = 4;

static const int CANNOT_FIND_INVERSE_MATRIX_ERROR_CODE = 5;

static const int CANNOT_FIND_LU_DECOMPOSITION_ERROR_CODE = 6;

static const int CANNOT_BUILD_LINEAR_REGRESSION_ERROR_CODE = 7;

static const int NOT_VALID_INVERSE_ALGORITHM_ERROR_CODE = 8;

// Текст помилок
static const char* MATRIX_IS_NOT_SQUARE_ERROR_TEXT = "MATRIX IS NOT SQUARE";

static const char* CANNOT_DIVIDE_BY_ZERO_ERROR_TEXT = "CANNOT DIVIDE BY ZERO";

static const char* CANNOT_ADD_OR_SUBTRACT_ERROR_TEXT = "CANNOT ADD OR SUBTRACT MATRICES OF DIFFERENT DIMENSIONS";

static const char* CANNOT_MULTIPLY_ERROR_TEXT = "CANNOT MULTIPLY MATRICES OF DIFFERENT DIMENSIONS";

static const char* CANNOT_FIND_INVERSE_MATRIX_ERROR_TEXT = "MATRIX IS NOT INVERTIBLE";

static const char* CANNOT_FIND_LU_DECOMPOSITION_ERROR_TEXT = "CANNOT FIND LU DECOMPOSITION";

static const char* CANNOT_BUILD_LINEAR_REGRESSION_ERROR_TEXT = "WRONG MATRICES DIMENSIONS FOR BUILDING LINEAR REGRESSION";

static const char* NOT_VALID_INVERSE_ALGORITHM_ERROR_TEXT = "NOT VALID INVERSE ALGORITHM. SUPPORTED ALGORITHMS: 'LU', 'Gauss-Jordan'";

static std::map<int, const char*> ERRORS_MAP = {
    {MATRIX_IS_NOT_SQUARE_ERROR_CODE, MATRIX_IS_NOT_SQUARE_ERROR_TEXT},
    {CANNOT_DIVIDE_BY_ZERO_ERROR_CODE, CANNOT_DIVIDE_BY_ZERO_ERROR_TEXT},
    {CANNOT_ADD_OR_SUBTRACT_ERROR_CODE, CANNOT_ADD_OR_SUBTRACT_ERROR_TEXT},
    {CANNOT_MULTIPLY_ERROR_CODE, CANNOT_MULTIPLY_ERROR_TEXT},
    {CANNOT_FIND_INVERSE_MATRIX_ERROR_CODE, CANNOT_FIND_INVERSE_MATRIX_ERROR_TEXT},
    {CANNOT_FIND_LU_DECOMPOSITION_ERROR_CODE, CANNOT_FIND_LU_DECOMPOSITION_ERROR_TEXT},
    {CANNOT_BUILD_LINEAR_REGRESSION_ERROR_CODE, CANNOT_BUILD_LINEAR_REGRESSION_ERROR_TEXT},
    {NOT_VALID_INVERSE_ALGORITHM_ERROR_CODE, NOT_VALID_INVERSE_ALGORITHM_ERROR_TEXT}
};

inline void printError(int error) {
    std::cout << "ERROR " << error << ": " << ERRORS_MAP[error] << std::endl;
}

#endif //ALGORITHMSGROUPPROJECTLU_ERRORS_H
