#ifndef ALGORITHMSGROUPPROJECTLU_ERRORS_H
#define ALGORITHMSGROUPPROJECTLU_ERRORS_H

#include <map>
#include <iostream>

using std::cout;
using std::endl;
using std::map;

const int CANNOT_FIND_INVERSE_MATRIX_ERROR_CODE = 1;

const int CANNOT_DIVIDE_BY_ZERO_ERROR_CODE = 2;

const int CANNOT_ADD_OR_SUBTRACT_ERROR_CODE = 3;

const int MATRIX_IS_NOT_SQUARE_ERROR_CODE = 4;

const int CANNOT_MULTIPLY_ERROR_CODE = 5;


const char* CANNOT_FIND_INVERSE_MATRIX_ERROR_TEXT = "MATRIX IS NOT INVERTIBLE: THE DETERMINANT IS ZERO";

const char* CANNOT_DIVIDE_BY_ZERO_ERROR_TEXT = "CANNOT DIVIDE BY ZERO";

const char* CANNOT_ADD_OR_SUBTRACT_ERROR_TEXT = "CANNOT ADD OR SUBTRACT MATRICES OF DIFFERENT DIMENSIONS";

const char* MATRIX_IS_NOT_SQUARE_ERROR_TEXT = "MATRIX IS NOT SQUARE";

const char* CANNOT_MULTIPLY_ERROR_TEXT = "CANNOT MULTIPLY MATRICES OF DIFFERENT DIMENSIONS";

map<int, const char*> ERRORS_MAP =
{
    {CANNOT_FIND_INVERSE_MATRIX_ERROR_CODE, CANNOT_FIND_INVERSE_MATRIX_ERROR_TEXT},
    {CANNOT_DIVIDE_BY_ZERO_ERROR_CODE, CANNOT_DIVIDE_BY_ZERO_ERROR_TEXT},
    {CANNOT_ADD_OR_SUBTRACT_ERROR_CODE, CANNOT_ADD_OR_SUBTRACT_ERROR_TEXT},
    {MATRIX_IS_NOT_SQUARE_ERROR_CODE, MATRIX_IS_NOT_SQUARE_ERROR_TEXT},
    {CANNOT_MULTIPLY_ERROR_CODE, CANNOT_MULTIPLY_ERROR_TEXT}
};

void printError(int error)
{
    cout << "ERROR " << error << ": " << ERRORS_MAP[error] << endl;
}

#endif //ALGORITHMSGROUPPROJECTLU_ERRORS_H
