Algorithms Group Project: Headers/Benchmarks.h File Reference
Benchmarks.h File Reference
#include "Headers/ComplexMatrix.h"
#include "LinearRegression.h"
#include <chrono>
Functions
void testInverseGaussJordan (ComplexMatrix< double > Matrix)
void testInverseLU (ComplexMatrix< double > Matrix)
void testStrassenAlgorithm (ComplexMatrix< double > Matrix)
void testRegularMultiplication (ComplexMatrix< double > Matrix)
void testBuildingLinearRegression (const ComplexMatrix< double > &Y, const ComplexMatrix< double > &X)
void timeTestInverseGaussJordan (int order=10, int accuracy=100)
void timeTestInverseLU (int order=10, int accuracy=100)
void timeTestStrassenAlgorithm (int rows=10, int columns=10, int accuracy=100)
void timeTestRegularMultiplication (int rows=10, int columns=10, int accuracy=100)
void timeLinearRegression (int varsAmount=5, int dataAmount=10, int accuracy=100)
Function Documentation
testBuildingLinearRegression()
void testBuildingLinearRegression (const ComplexMatrix< double > & Y, const ComplexMatrix< double > & X)
Definition at line 28 of file Benchmarks.h.
{
    LinearRegression<double> regression(Y, X);
}
Referenced by timeLinearRegression().
testInverseGaussJordan()
void testInverseGaussJordan (ComplexMatrix< double > Matrix)
Definition at line 12 of file Benchmarks.h.
{
    Matrix.getInverse("Gauss-Jordan");
}
References ComplexMatrix< T >::getInverse().
Referenced by timeTestInverseGaussJordan().
testInverseLU()
void testInverseLU (ComplexMatrix< double > Matrix)
Definition at line 16 of file Benchmarks.h.
{
    Matrix.getInverse("LU");
}
References ComplexMatrix< T >::getInverse().
Referenced by timeTestInverseLU().
testRegularMultiplication()
void testRegularMultiplication (ComplexMatrix< double > Matrix)
Definition at line 24 of file Benchmarks.h.
{
    Matrix * Matrix;
}
Referenced by timeTestRegularMultiplication().
testStrassenAlgorithm()
void testStrassenAlgorithm (ComplexMatrix< double > Matrix)
Definition at line 20 of file Benchmarks.h.
{
    Matrix.StrassenMultiply(Matrix);
}
References ComplexMatrix< T >::StrassenMultiply().
Referenced by timeTestStrassenAlgorithm().
timeLinearRegression()
void timeLinearRegression (int varsAmount = 5, int dataAmount = 10, int accuracy = 100)
Definition at line 121 of file Benchmarks.h.
{
    cout << endl;
    auto start = high_resolution_clock::now();
    auto creationStart = start;
    auto creationStop = start;
    for (int i = 0; i < accuracy; ++i) {
        creationStart = high_resolution_clock::now();
        ComplexMatrix<double> Y = ComplexMatrix<double>::getRandom(dataAmount, 1);
        ComplexMatrix<double> X = ComplexMatrix<double>::getRandom(dataAmount, varsAmount);
        creationStop = high_resolution_clock::now();
        start -= (creationStart - creationStop);
        testBuildingLinearRegression(Y, X);
    }
    auto stop = high_resolution_clock::now();
    auto duration = duration_cast<microseconds>(stop - start);
    long long int res = duration.count()/accuracy;
    cout << "Середній час виконання алгоритму побудови лінійної регресії: ";
    cout << res / 1000000 << " секунд, "
         << (res % 1000000) / 1000 << " мілісекунд i "
         << res % 1000 << " мікросекунд" << endl;
    cout << endl;
}
References ComplexMatrix< T >::getRandom(), and testBuildingLinearRegression().
Referenced by main().
timeTestInverseGaussJordan()
void timeTestInverseGaussJordan (int order = 10, int accuracy = 100)
Definition at line 32 of file Benchmarks.h.
{
    cout << endl;
    auto start = high_resolution_clock::now();
    auto creationStart = start;
    auto creationStop = start;
    for (int i = 0; i < accuracy; ++i) {
        creationStart = high_resolution_clock::now();
        ComplexMatrix<double> Test = ComplexMatrix<double>::getRandom(order, order);
        creationStop = high_resolution_clock::now();
        start -= (creationStart - creationStop);
        testInverseGaussJordan(Test);
    }
    auto stop = high_resolution_clock::now();
    auto duration = duration_cast<microseconds>(stop - start);
    long long int res = duration.count() / accuracy;
    cout << "Середній час виконання алгоритму інверсії методом Жордана-Гауса: ";
    cout << res / 1000000 << " секунд, "
         << (res % 1000000) / 1000 << " мілісекунд i "
         << res % 1000 << " мікросекунд" << endl;
    cout << endl;
}
References ComplexMatrix< T >::getRandom(), and testInverseGaussJordan().
Referenced by main().
timeTestInverseLU()
void timeTestInverseLU (int order = 10, int accuracy = 100)
Definition at line 55 of file Benchmarks.h.
{
    cout << endl;
    auto start = high_resolution_clock::now();
    auto creationStart = start;
    auto creationStop = start;
    for (int i = 0; i < accuracy; ++i) {
        creationStart = high_resolution_clock::now();
        ComplexMatrix<double> Test = ComplexMatrix<double>::getRandom(order, order);
        creationStop = high_resolution_clock::now();
        start -= (creationStart - creationStop);
        testInverseLU(Test);
    }
    auto stop = high_resolution_clock::now();
    auto duration = duration_cast<microseconds>(stop - start);
    long long int res = duration.count()/accuracy;
    cout << "Середній час виконання алгоритму інверсії LU розкладанням: ";
    cout << res / 1000000 << " секунд, "
         << (res % 1000000) / 1000 << " мілісекунд i "
         << res % 1000 << " мікросекунд" << endl;
    cout << endl;
}
References ComplexMatrix< T >::getRandom(), and testInverseLU().
Referenced by main().
timeTestRegularMultiplication()
void timeTestRegularMultiplication (int rows = 10, int columns = 10, int accuracy = 100)
Definition at line 101 of file Benchmarks.h.
{
    cout << endl;
    auto start = high_resolution_clock::now();
    auto creationStart = start;
    auto creationStop = start;
    for (int i = 0; i < accuracy; ++i) {
        ComplexMatrix<double> Test = ComplexMatrix<double>::getRandom(rows, columns);
        testRegularMultiplication(Test);
    }
    auto stop = high_resolution_clock::now();
    auto duration = duration_cast<microseconds>(stop - start);
    long long int res = duration.count()/accuracy;
    cout << "Середній час виконання алгоритму звичайного множення: ";
    cout << res / 1000000 << " секунд, "
         << (res % 1000000) / 1000 << " мілісекунд i "
         << res % 1000 << " мікросекунд" << endl;
    cout << endl;
}
References ComplexMatrix< T >::getRandom(), and testRegularMultiplication().
Referenced by main().
timeTestStrassenAlgorithm()
void timeTestStrassenAlgorithm (int rows = 10, int columns = 10, int accuracy = 100)
Definition at line 78 of file Benchmarks.h.
{
    cout << endl;
    auto start = high_resolution_clock::now();
    auto creationStart = start;
    auto creationStop = start;
    for (int i = 0; i < accuracy; ++i) {
        creationStart = high_resolution_clock::now();
        ComplexMatrix<double> Test = ComplexMatrix<double>::getRandom(rows, columns);
        creationStop = high_resolution_clock::now();
        start -= (creationStart - creationStop);
        testStrassenAlgorithm(Test);
    }
    auto stop = high_resolution_clock::now();
    auto duration = duration_cast<microseconds>(stop - start);
    long long int res = duration.count()/accuracy;
    cout << "Середній час виконання алгоритму Штрассена: ";
    cout << res / 1000000 << " секунд, "
         << (res % 1000000) / 1000 << " мілісекунд i "
         << res % 1000 << " мікросекунд" << endl;
    cout << endl;
}
References ComplexMatrix< T >::getRandom(), and testStrassenAlgorithm().
Referenced by main().