Algorithms Group Project: Cpp/Unit tests/Test Linear Regression.cpp File Reference
Test Linear Regression.cpp File Reference
#include "Headers/Doctest/doctest.h"
#include "Headers/LinearRegression.h"
Functions
Complex< double > testAndGetErrorDifference (int varsAmount, int dataAmount, Complex< double > maxDeviation)
TEST_CASE ("Test Linear Regression Errors")
TEST_CASE ("Test Linear Regression Work")
Function Documentation
TEST_CASE() [1/2]
TEST_CASE ("Test Linear Regression Errors")
Definition at line 33 of file Test Linear Regression.cpp.
{
    SUBCASE("Y has more than one column") {
        ComplexMatrix<double> Y = ComplexMatrix<double>(2, 2);
        ComplexMatrix<double> X = ComplexMatrix<double>(2, 1);
        try {
            LinearRegression<double> lr(Y, X);
        }
        catch (LinearRegression<double>& lr) {
            CHECK(lr.getCoefficients().size() == 0);
        }
    }
    SUBCASE("Y and X has different amount of rows") {
        ComplexMatrix<double> Y = ComplexMatrix<double>(4, 1);
        ComplexMatrix<double> X = ComplexMatrix<double>(5, 2);
        try {
            LinearRegression<double> lr(Y, X);
        }
        catch (LinearRegression<double>& lr) {
            CHECK(lr.getCoefficients().size() == 0);
        }
    }
    SUBCASE("X has less or equal rows than columns (not enough data for building linear regression)") {
        ComplexMatrix<double> Y = ComplexMatrix<double>(4, 1);
        ComplexMatrix<double> X = ComplexMatrix<double>(4, 4);
        try {
            LinearRegression<double> lr(Y, X);
        }
        catch (LinearRegression<double>& lr) {
            CHECK(lr.getCoefficients().size() == 0);
        }
    }
}
References CHECK, LinearRegression< T >::getCoefficients(), and SUBCASE.
TEST_CASE() [2/2]
TEST_CASE ("Test Linear Regression Work")
Definition at line 67 of file Test Linear Regression.cpp.
{
    SUBCASE("Small amount of data and small deviation") {
        CHECK((testAndGetErrorDifference(1, 5, Complex<double>(0.5, 0)) <= 1e-5));
    }
    SUBCASE("Small amount of data and medium deviation") {
        CHECK((testAndGetErrorDifference(1, 5, Complex<double>(10, 0)) <= 1e-5));
    }
    SUBCASE("Small amount of data and big deviation") {
        CHECK((testAndGetErrorDifference(1, 5, Complex<double>(100, 0)) <= 1e-5));
    }
    SUBCASE("Medium amount of data and small deviation") {
        CHECK((testAndGetErrorDifference(50, 100, Complex<double>(0.5, 0)) <= 1e-5));
    }
    SUBCASE("Medium amount of data and medium deviation") {
        CHECK((testAndGetErrorDifference(50, 100, Complex<double>(10, 0)) <= 1e-5));
    }
    SUBCASE("Medium amount of data and big deviation") {
        CHECK((testAndGetErrorDifference(50, 100, Complex<double>(100, 0)) <= 1e-5));
    }
    SUBCASE("Big amount of data and small deviation") {
        CHECK((testAndGetErrorDifference(200, 400, Complex<double>(0.5, 0)) <= 1e-5));
    }
    SUBCASE("Big amount of data and medium deviation") {
        CHECK((testAndGetErrorDifference(200, 400, Complex<double>(10, 0)) <= 1e-5));
    }
    SUBCASE("Big amount of data and big deviation") {
        CHECK((testAndGetErrorDifference(200, 400, Complex<double>(100, 0)) <= 1e-5));
    }
}
References CHECK, SUBCASE, and testAndGetErrorDifference().
testAndGetErrorDifference()
Complex< double > testAndGetErrorDifference (int varsAmount, int dataAmount, Complex< double > maxDeviation)
Definition at line 4 of file Test Linear Regression.cpp.
{
    ComplexMatrix<double> Y = ComplexMatrix<double>(dataAmount, 1);
    ComplexMatrix<double> X = ComplexMatrix<double>(dataAmount, varsAmount);
    vector<Complex<double>> randCoefficients;
    Complex<double> maxMSE(0);
    for (int i = 0; i <= varsAmount; i++) {
        randCoefficients.emplace_back(Complex<double>::getRandomNumber(-500, 500, true, false).getReal());
    }
    for (int i = 0; i < dataAmount; i++) {
        Complex<double> yReg = randCoefficients[0];
        for (int j = 0; j < varsAmount; j++) {
            Complex<double> randX(Complex<double>::getRandomNumber(-500, 500, true, false));
            X[i][j] = randX;
            yReg += randCoefficients[j + 1] * randX;
        }
        Complex<double> deviation = Complex<double>::getRandomNumber(-(double)INT_MAX, (double)INT_MAX, true, false) * maxDeviation;
        maxMSE += deviation * deviation;
        Y[i][0] = yReg + deviation;
    }
    LinearRegression<double> lr(Y, X);
    return lr.getMeanSquaredError() - maxMSE;
}
References LinearRegression< T >::getMeanSquaredError(), and Complex< T >::getRandomNumber().
Referenced by TEST_CASE().