Algorithms Group Project: Cpp/Unit tests/Test Strassen Algorithm.cpp File Reference
Test Strassen Algorithm.cpp File Reference
#include "Headers/ComplexMatrix.h"
#include "Headers/Doctest/doctest.h"
Functions
template<typename T >
void testMultiplicationErrorDifference (int order, T epsilon)
TEST_CASE ("Test getInverseGaussJordan Errors")
TEST_CASE ("Test StrassenAlgorithm Work")
Function Documentation
TEST_CASE() [1/2]
TEST_CASE ("Test getInverseGaussJordan Errors")
Definition at line 18 of file Test Strassen Algorithm.cpp.
{
    ComplexMatrix<double> Matrix1(10,9);
    ComplexMatrix<double> Matrix2(10 ,9);
    CHECK(Matrix1 == (Matrix1.StrassenMultiply(Matrix2)));
}
References CHECK, and ComplexMatrix< T >::StrassenMultiply().
TEST_CASE() [2/2]
TEST_CASE ("Test StrassenAlgorithm Work")
Definition at line 24 of file Test Strassen Algorithm.cpp.
{
    SUBCASE("float test") {
        SUBCASE("10x10 test") {
            testMultiplicationErrorDifference(65, 0);
        }
        SUBCASE("100x100 test") {
            testMultiplicationErrorDifference(128, 0);
        }
    }
    SUBCASE("double test") {
        SUBCASE("10x10 test") {
            testMultiplicationErrorDifference(65, 0);
        }
        SUBCASE("100x100 test") {
            testMultiplicationErrorDifference(128, 0);
        }
    }
}
References SUBCASE, and testMultiplicationErrorDifference().
testMultiplicationErrorDifference()
template<typename T > void testMultiplicationErrorDifference (int order, T epsilon)
Definition at line 4 of file Test Strassen Algorithm.cpp.
{
    ComplexMatrix<T> Matrix1 = ComplexMatrix<T>::getRandom(order, order);
    ComplexMatrix<T> Matrix2 = ComplexMatrix<T>::getRandom(order, order);
    ComplexMatrix<T> Strassen = Matrix1.StrassenMultiply(Matrix2);
    ComplexMatrix<T> Regular = Matrix1 * Matrix2;
    for (int i = 0; i < order; i++)
    {
        for (int j = 0; j < order; j++)
        {
            REQUIRE((Strassen[i][j] - Regular[i][j]).abs() <= epsilon);
        }
    }
}
References ComplexMatrix< T >::getRandom(), REQUIRE, and ComplexMatrix< T >::StrassenMultiply().
Referenced by TEST_CASE().