Algorithms Group Project: LinearRegression< T > Class Template Reference
LinearRegression< T > Class Template Reference
Linear Regression class.
#include <LinearRegression.h>
Public Member Functions
LinearRegression (ComplexMatrix< T > Y, ComplexMatrix< T > X)
Run linear regression algorithm.
vector< Complex< T > > getCoefficients ()
Find linear regression coefficients.
Complex< T > getMeanSquaredError ()
Find linear regression error.
Private Attributes
vector< Complex< T > > coefficients
Complex< T > meanSquaredError
Detailed Description
template<typename T>
class LinearRegression< T >
Linear Regression class.
Template Parameters
T - type
Definition at line 11 of file LinearRegression.h.
Constructor & Destructor Documentation
LinearRegression()
template<typename T > LinearRegression< T >::LinearRegression (ComplexMatrix< T > Y, ComplexMatrix< T > X) inline
Run linear regression algorithm.
Template Parameters
T - type
Parameters
Y - matrix of target values
X - matrix of features
Definition at line 23 of file LinearRegression.h.
{
        if (Y.getColumns() != 1 || Y.getRows() != X.getRows() || X.getRows() <= X.getColumns()) {
            printError(CANNOT_BUILD_LINEAR_REGRESSION_ERROR_CODE);
            throw (*this);
        }
        ComplexMatrix<T> NewX(X.getRows(), X.getColumns() + 1);
        ComplexMatrix<T> NewXTransposed(X.getColumns() + 1, X.getRows());
        ComplexMatrix<T> CoefficientsMatrix;
        vector<Complex<T>> coefficientsVector;
        Complex<T> mse(0, 0);
        for (int i = 0; i < X.getRows(); i++) {
            NewX[i][0] = Complex<T>(1, 0);
            for (int j = 1; j <= X.getColumns(); j++) {
                NewX[i][j] = X[i][j - 1];
            }
        }
        NewXTransposed = NewX.getTransposed();
        CoefficientsMatrix = (NewXTransposed * NewX).getInverse("Gauss-Jordan") * NewXTransposed * Y;
        for (int i = 0; i < CoefficientsMatrix.getRows(); i++) {
            coefficientsVector.push_back(CoefficientsMatrix[i][0]);
        }
        for (int i = 0; i < Y.getRows(); i++) {
            Complex<T> yReg(0, 0);
            for (int j = 0; j < NewX.getColumns(); j++) {
                yReg += NewX[i][j] * coefficientsVector[j];
            }
            mse += (Y[i][0] - yReg) * (Y[i][0] - yReg);
        }
        mse /= Complex<T>(Y.getRows(), 0);
        this->coefficients = coefficientsVector;
        this->meanSquaredError = mse;
    }
References ComplexMatrix< T >::getColumns(), ComplexMatrix< T >::getRows(), ComplexMatrix< T >::getTransposed(), and printError().
Member Function Documentation
getCoefficients()
template<typename T > vector< Complex< T > > LinearRegression< T >::getCoefficients () inline
Find linear regression coefficients.
Returns
vector of coefficients
Definition at line 71 of file LinearRegression.h.
{
        return this->coefficients;
    }
References LinearRegression< T >::coefficients.
Referenced by TEST_CASE().
getMeanSquaredError()
template<typename T > Complex< T > LinearRegression< T >::getMeanSquaredError () inline
Find linear regression error.
Returns
meanSquaredError
Definition at line 79 of file LinearRegression.h.
{
        return this->meanSquaredError;
    }
References LinearRegression< T >::meanSquaredError.
Referenced by testAndGetErrorDifference().
Member Data Documentation
coefficients
template<typename T > vector<Complex<T> > LinearRegression< T >::coefficients private
Definition at line 13 of file LinearRegression.h.
Referenced by LinearRegression< T >::getCoefficients().
meanSquaredError
template<typename T > Complex<T> LinearRegression< T >::meanSquaredError private
Definition at line 14 of file LinearRegression.h.
Referenced by LinearRegression< T >::getMeanSquaredError().
The documentation for this class was generated from the following file:
Headers/LinearRegression.h