Algorithms Group Project: ComplexMatrix< T > Class Template Reference
ComplexMatrix< T > Class Template Reference
Complex Matrix class.
#include <ComplexMatrix.h>
Public Member Functions
ComplexMatrix ()=default
Default constructor.
ComplexMatrix (const ComplexMatrix &Matrix)
Copy constructor.
ComplexMatrix (const int &N, const int &M)
Create N by M matrix with zeroes O(n*m)
ComplexMatrix (const int &N)
Create N by N matrix with zeroes O(n^2)
unsigned int getColumns ()
Find number of columns.
unsigned int getRows ()
Find number of rows.
ComplexMatrix< T > getInverse (const std::string &algorithm)
Find inverse matrix using one of supported algorithms.
ComplexMatrix< T > getTransposed ()
Find transposed matrix O(n^2)
vector< Complex< T > > & operator[] (const int &i)
Get [i] row O(1)
ComplexMatrix< T > operator+ (ComplexMatrix< T > Matrix)
Add two matrices O(n*m)
ComplexMatrix< T > operator- (ComplexMatrix< T > Matrix)
Subtract two matrices O(n*m)
bool operator== (ComplexMatrix< T > Matrix)
Check if two matrices are equal O(n*m)
ComplexMatrix< T > operator* (ComplexMatrix< T > Matrix)
Multiply two matrices O(n^3)
ComplexMatrix< T > StrassenMultiply (ComplexMatrix< T > Matrix)
Multiply two matrices using Strassen Multiply O(n^(log2(7))) ~ O(n^2.8074) if n <= 64 O(n^3)
void print ()
Print matrix O(n*m)
Static Public Member Functions
static ComplexMatrix< T > getIdentity (const int &N)
Create N by N identity matrix O(n^2)
static ComplexMatrix< T > getRandom (const int &N, const int &M, T range=INT_MAX)
Create N by M matrix with random numbers O(n*m)
Private Member Functions
void swapRows (const int &firstRow, const int &secondRow)
Swaps two rows of a matrix.
void swapColumns (const int &firstColumn, const int &secondColumn)
Swaps two columns of a matrix.
bool getLUDecomposition (ComplexMatrix< T > &Decomposition, ComplexMatrix< T > &Permutations)
Find LU decomposition of a matrix.
void StrassenMultiplication (ComplexMatrix< T > A, ComplexMatrix< T > B, ComplexMatrix< T > &Product)
Multiply two matrices using Strassen algorithm.
ComplexMatrix< T > getInverseGaussJordan ()
Find inverse matrix using Gauss-Jordan method О(n^3)
ComplexMatrix< T > getInverseLU ()
Find inverse matrix using LU-decomposition method О(n^3)
Private Attributes
unsigned int rows {}
unsigned int columns {}
vector< vector< Complex< T > > > matrix
Detailed Description
template<typename T>
class ComplexMatrix< T >
Complex Matrix class.
Template Parameters
T type
Definition at line 16 of file ComplexMatrix.h.
Constructor & Destructor Documentation
ComplexMatrix() [1/4]
template<typename T > ComplexMatrix< T >::ComplexMatrix () default
Default constructor.
Referenced by ComplexMatrix< T >::getInverseGaussJordan(), and ComplexMatrix< T >::getLUDecomposition().
ComplexMatrix() [2/4]
template<typename T > ComplexMatrix< T >::ComplexMatrix (const ComplexMatrix< T > & Matrix) inline
Copy constructor.
Parameters
Matrix - matrix to be copied
Definition at line 280 of file ComplexMatrix.h.
{
        this->rows = Matrix.rows;
        this->columns = Matrix.columns;
        this->matrix = Matrix.matrix;
    }
References ComplexMatrix< T >::columns, ComplexMatrix< T >::matrix, and ComplexMatrix< T >::rows.
ComplexMatrix() [3/4]
template<typename T > ComplexMatrix< T >::ComplexMatrix (const int & N, const int & M) inline
Create N by M matrix with zeroes O(n*m)
Parameters
N - rows
M - columns
Definition at line 292 of file ComplexMatrix.h.
{
        this->rows = N;
        this->columns = M;
        for (int i = 0; i < this->rows; ++i) {
            vector<Complex<T>> line;
            for (int j = 0; j < this->columns; ++j) {
                Complex<T> number;
                line.push_back(number);
            }
            matrix.push_back(line);
        }
    }
References ComplexMatrix< T >::columns, ComplexMatrix< T >::matrix, and ComplexMatrix< T >::rows.
ComplexMatrix() [4/4]
template<typename T > ComplexMatrix< T >::ComplexMatrix (const int & N) inline explicit
Create N by N matrix with zeroes O(n^2)
Parameters
N - rows, columns
Definition at line 310 of file ComplexMatrix.h.
{
        (*this) = ComplexMatrix<T>(N, N);
    }
Member Function Documentation
getColumns()
template<typename T > unsigned int ComplexMatrix< T >::getColumns () inline
Find number of columns.
Returns
number of columns
Definition at line 318 of file ComplexMatrix.h.
{
        return this->columns;
    }
References ComplexMatrix< T >::columns.
Referenced by LinearRegression< T >::LinearRegression().
getIdentity()
template<typename T > static ComplexMatrix< T > ComplexMatrix< T >::getIdentity (const int & N) inline static
Create N by N identity matrix O(n^2)
Parameters
N - rows, columns
Definition at line 335 of file ComplexMatrix.h.
{
        ComplexMatrix<T> Identity(N);
        for (int i = 0; i < N; i++) {
            Identity[i][i].setReal(1);
        }
        return Identity;
    }
Referenced by ComplexMatrix< T >::getInverseGaussJordan(), ComplexMatrix< T >::getLUDecomposition(), and testInverseErrorDifference().
getInverse()
template<typename T > ComplexMatrix< T > ComplexMatrix< T >::getInverse (const std::string & algorithm) inline
Find inverse matrix using one of supported algorithms.
Parameters
algorithm - name of the inverse method. Supported: "LU", "Gauss-Jordan".
Returns
inverse matrix
Definition at line 365 of file ComplexMatrix.h.
{
        if (algorithm == "LU") {
            return this->getInverseLU();
        }
        else if (algorithm == "Gauss-Jordan") {
            return this->getInverseGaussJordan();
        }
        printError(NOT_VALID_INVERSE_ALGORITHM_ERROR_CODE);
        return *this;
    }
References ComplexMatrix< T >::getInverseGaussJordan(), ComplexMatrix< T >::getInverseLU(), and printError().
Referenced by TEST_CASE(), TEST_CASE(), testInverseErrorDifference(), testInverseGaussJordan(), and testInverseLU().
getInverseGaussJordan()
template<typename T > ComplexMatrix< T > ComplexMatrix< T >::getInverseGaussJordan () inline private
Find inverse matrix using Gauss-Jordan method О(n^3)
Returns
inverse matrix
Definition at line 156 of file ComplexMatrix.h.
{
        // Якщо матриця не квадратна
        if (this->columns != this->rows) {
            printError(MATRIX_IS_NOT_SQUARE_ERROR_CODE);
            return *this;
        }
        // Одинична матриця
        ComplexMatrix<T> Identity = ComplexMatrix<T>::getIdentity(this->rows);
        // Копія, щоб не змінювати реальну
        ComplexMatrix<T> MatrixCopy = ComplexMatrix(*this);
        for (int i = 0; i < this->rows; i++) {
            // Якщо 0, то шукаємо перший ненульовий і свапаємо
            if (MatrixCopy[i][i] == 0) {
                int supportElement = i + 1;
                while (supportElement < this->rows && MatrixCopy[supportElement][i] == 0) {
                    supportElement++;
                }
                if (supportElement == this->rows) {
                    printError(CANNOT_FIND_INVERSE_MATRIX_ERROR_CODE);
                    return *this;
                }
                MatrixCopy.swapRows(i, supportElement);
                Identity.swapRows(i, supportElement);
            }
            // Ділимо на a + bi
            Complex<T> divider = MatrixCopy[i][i];
            for (int j = 0; j < this->rows; j++) {
                Identity[i][j] /= divider;
            }
            for (int j = i + 1; j < this->rows; j++) {
                MatrixCopy[i][j] /= divider;
            }
            // Елементи під діагоналлю в 0
            for (int k = i + 1; k < this->rows; k++) {
                Complex<T> factor = MatrixCopy[k][i];
                for (int j = 0; j < this->rows; j++) {
                    if (j >= i) MatrixCopy[k][j] -= (MatrixCopy[i][j] * factor);
                    Identity[k][j] -= (Identity[i][j] * factor);
                }
            }
            // Елементи над діагоналлю в 0
            for (int k = i - 1; k >= 0; k--) {
                Complex<T> factor = MatrixCopy[k][i];
                for (int j = 0; j < this->rows; j++) {
                    if (j >= i) MatrixCopy[k][j] -= (MatrixCopy[i][j] * factor);
                    Identity[k][j] -= (Identity[i][j] * factor);
                }
            }
        }
        return Identity;
    }
References ComplexMatrix< T >::columns, ComplexMatrix< T >::ComplexMatrix(), ComplexMatrix< T >::getIdentity(), printError(), ComplexMatrix< T >::rows, and ComplexMatrix< T >::swapRows().
Referenced by ComplexMatrix< T >::getInverse().
getInverseLU()
template<typename T > ComplexMatrix< T > ComplexMatrix< T >::getInverseLU () inline private
Find inverse matrix using LU-decomposition method О(n^3)
Returns
inverse matrix
Definition at line 221 of file ComplexMatrix.h.
{
        if (this->columns != this->rows) {
            printError(MATRIX_IS_NOT_SQUARE_ERROR_CODE);
            return *this;
        }
        ComplexMatrix<T> Decomposition, Permutation;
        if (getLUDecomposition(Decomposition, Permutation) == false) {
            printError(CANNOT_FIND_INVERSE_MATRIX_ERROR_CODE);
            return *this;
        }
        // Спробував через заміни, чомусь працює
        ComplexMatrix<T> Inverse(this->rows);
        vector<Complex<T>> D(this->rows);
        for (int i = 0; i < this->rows; i++) {
            // forward substitution
            for (int j = 0; j < this->rows; j++) {
                Complex<T> numerator = i == j ? Complex<T>(1, 0) : Complex<T>(0, 0);
                for (int k = 0; k < j; k++) {
                    numerator -= Decomposition[j][k] * D[k];
                }
                D[j] = numerator;
            }
            // backward substitution
            for (int j = this->rows - 1; j >= 0; j--) {
                Complex<T> numerator = D[j] ;
                for (int k = j + 1; k < this->rows; k++) {
                    numerator -= Decomposition[j][k] * Inverse[k][i];
                }
                Inverse[j][i] = numerator / Decomposition[j][j];
            }
        }
        for (int i = this->rows - 1; i >= 0; i--) {
            for (int j = 0; j < i; j++) {
                if (Permutation[i][j] != Complex<T>(1, 0)) {
                    continue;
                }
                Permutation.swapRows(i, j);
                Inverse.swapColumns(i, j);
                i++;
                break;
            }
        }
        return Inverse;
    }
References ComplexMatrix< T >::columns, ComplexMatrix< T >::getLUDecomposition(), printError(), ComplexMatrix< T >::rows, ComplexMatrix< T >::swapColumns(), and ComplexMatrix< T >::swapRows().
Referenced by ComplexMatrix< T >::getInverse().
getLUDecomposition()
template<typename T > bool ComplexMatrix< T >::getLUDecomposition (ComplexMatrix< T > & Decomposition, ComplexMatrix< T > & Permutations) inline private
Find LU decomposition of a matrix.
Parameters
Decomposition - matrix that will contain the decomposition
Permutations - matrix that will contain the permutations
Returns
True if there exists a decomposition and false if not
Definition at line 55 of file ComplexMatrix.h.
{
        // Верхня, нижня трикутні матриці та матриця перестановок
        if (this->columns != this->rows) {
            printError(CANNOT_FIND_LU_DECOMPOSITION_ERROR_CODE);
            return false;
        }
        // Верхня трикутна матриця, нижня трикутні матриці
        // зберігаються в Decomposition
        // Decomposition = Lower + Upper - E
        // E - одинична матриця
        Decomposition = ComplexMatrix(*this),
                Permutations = ComplexMatrix::getIdentity(this->rows);
        for (int i = 0; i < rows; i++) {
            // Пошук опорного елемента
            int supportElement = i;
            while (supportElement < this->rows && Decomposition[supportElement][i] == 0) {
                supportElement++;
            }
            if (supportElement == this->rows) {
                printError(CANNOT_FIND_LU_DECOMPOSITION_ERROR_CODE);
                return false;
            }
            // Міняємо місцями i-ту рядок і рядок з опорним елементом
            Permutations.swapRows(supportElement, i);
            Decomposition.swapRows(supportElement, i);
            for (int j = i + 1; j < rows; j++) {
                Decomposition[j][i] /= Decomposition[i][i];
                for (int k = i + 1; k < rows; k++)
                    Decomposition[j][k] -= Decomposition[j][i] * Decomposition[i][k];
            }
        }
        return true;
    }
References ComplexMatrix< T >::columns, ComplexMatrix< T >::ComplexMatrix(), ComplexMatrix< T >::getIdentity(), printError(), ComplexMatrix< T >::rows, and ComplexMatrix< T >::swapRows().
Referenced by ComplexMatrix< T >::getInverseLU().
getRandom()
template<typename T > static ComplexMatrix< T > ComplexMatrix< T >::getRandom (const int & N, const int & M, T range = INT_MAX) inline static
Create N by M matrix with random numbers O(n*m)
Parameters
N - rows
M - columns
range - range of random numbers (-range, range)
Definition at line 350 of file ComplexMatrix.h.
{
        ComplexMatrix<T> Random(N, M);
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < M; j++) {
                Random[i][j] = Complex<T>::getRandomNumber(-range, range);
            }
        }
        return Random;
    }
References Complex< T >::getRandomNumber().
Referenced by TEST_CASE(), TEST_CASE(), testInverseErrorDifference(), testMultiplicationErrorDifference(), timeLinearRegression(), timeTestInverseGaussJordan(), timeTestInverseLU(), timeTestRegularMultiplication(), and timeTestStrassenAlgorithm().
getRows()
template<typename T > unsigned int ComplexMatrix< T >::getRows () inline
Find number of rows.
Returns
number of rows
Definition at line 326 of file ComplexMatrix.h.
{
        return this->rows;
    }
References ComplexMatrix< T >::rows.
Referenced by LinearRegression< T >::LinearRegression().
getTransposed()
template<typename T > ComplexMatrix< T > ComplexMatrix< T >::getTransposed () inline
Find transposed matrix O(n^2)
Returns
transposed matrix
Definition at line 381 of file ComplexMatrix.h.
{
        ComplexMatrix<T> Transposed(this->columns, this->rows);
        for (int i = 0; i < this->rows; i++) {
            for (int j = 0; j < this->columns; j++) {
                Transposed[j][i] = (*this)[i][j];
            }
        }
        return Transposed;
    }
References ComplexMatrix< T >::columns, and ComplexMatrix< T >::rows.
Referenced by LinearRegression< T >::LinearRegression().
operator*()
template<typename T > ComplexMatrix< T > ComplexMatrix< T >::operator* (ComplexMatrix< T > Matrix) inline
Multiply two matrices O(n^3)
Parameters
Matrix - right matrix
Returns
product
Definition at line 467 of file ComplexMatrix.h.
{
        if (this->columns != Matrix.rows) {
            printError(CANNOT_MULTIPLY_ERROR_CODE);
            return *this;
        }
        ComplexMatrix<T> Product(this->rows, Matrix.columns);
        for (int i = 0; i < this->rows; i++) {
            for (int j = 0; j < Matrix.columns; j++) {
                for (int k = 0; k < Matrix.rows; k++) {
                    Product[i][j] += (*this)[i][k] * Matrix[k][j];
                }
            }
        }
        return Product;
    }
References ComplexMatrix< T >::columns, printError(), and ComplexMatrix< T >::rows.
operator+()
template<typename T > ComplexMatrix< T > ComplexMatrix< T >::operator+ (ComplexMatrix< T > Matrix) inline
Add two matrices O(n*m)
Parameters
Matrix - right matrix
Returns
sum
Definition at line 407 of file ComplexMatrix.h.
{
        if (this->rows != Matrix.rows || this->columns != Matrix.columns) {
            printError(CANNOT_ADD_OR_SUBTRACT_ERROR_CODE);
            return *this;
        }
        ComplexMatrix<T> Result(this->rows, this->columns);
        for (int i = 0; i < this->rows; i++) {
            for (int j = 0; j < this->columns; j++) {
                Result[i][j] = (*this)[i][j] + Matrix[i][j];
            }
        }
        return Result;
    }
References ComplexMatrix< T >::columns, printError(), and ComplexMatrix< T >::rows.
operator-()
template<typename T > ComplexMatrix< T > ComplexMatrix< T >::operator- (ComplexMatrix< T > Matrix) inline
Subtract two matrices O(n*m)
Parameters
Matrix - right matrix
Returns
difference
Definition at line 427 of file ComplexMatrix.h.
{
        if (this->rows != Matrix.rows || this->columns != Matrix.columns) {
            printError(CANNOT_ADD_OR_SUBTRACT_ERROR_CODE);
            return *this;
        }
        ComplexMatrix<T> Result(this->rows, this->columns);
        for (int i = 0; i < this->rows; i++) {
            for (int j = 0; j < this->columns; j++) {
                Result[i][j] = (*this)[i][j] - Matrix[i][j];
            }
        }
        return Result;
    }
References ComplexMatrix< T >::columns, printError(), and ComplexMatrix< T >::rows.
operator==()
template<typename T > bool ComplexMatrix< T >::operator== (ComplexMatrix< T > Matrix) inline
Check if two matrices are equal O(n*m)
Parameters
Matrix - right matrix
Returns
True if they are equal, false otherwise
Definition at line 447 of file ComplexMatrix.h.
{
        if (this->rows != Matrix.rows || this->columns != Matrix.columns) {
            return false;
        }
        for (int i = 0; i < this->rows; i++) {
            for (int j = 0; j < this->columns; j++) {
                if ((*this)[i][j] != Matrix[i][j]) {
                    return false;
                }
            }
        }
        return true;
    }
References ComplexMatrix< T >::columns, and ComplexMatrix< T >::rows.
operator[]()
template<typename T > vector< Complex< T > > & ComplexMatrix< T >::operator[] (const int & i) inline
Get [i] row O(1)
Parameters
i - row number from 0 to n
Returns
Definition at line 397 of file ComplexMatrix.h.
{
        return this->matrix[i];
    }
print()
template<typename T > void ComplexMatrix< T >::print () inline
Print matrix O(n*m)
Definition at line 527 of file ComplexMatrix.h.
{
        cout << endl;
        for (int i = 0; i < this->rows; i++) {
            for (int j = 0; j < this->columns; j++) {
                this->matrix[i][j].print();
            }
            cout << endl;
            cout << endl;
        }
        cout << endl;
    }
References ComplexMatrix< T >::columns, and ComplexMatrix< T >::rows.
StrassenMultiplication()
template<typename T > void ComplexMatrix< T >::StrassenMultiplication (ComplexMatrix< T > A, ComplexMatrix< T > B, ComplexMatrix< T > & Product) inline private
Multiply two matrices using Strassen algorithm.
Parameters
A - left matrix
B - right matrix
Product - matrix that will contain their product
Definition at line 98 of file ComplexMatrix.h.
{
        // База
        if (A.rows <= 64 || A.columns || B.columns) {
            Product = A * B;
            return;
        }
        int newSize = A.rows / 2;
        ComplexMatrix<T>
                a11(newSize), a12(newSize), a21(newSize), a22(newSize),
                b11(newSize), b12(newSize), b21(newSize), b22(newSize),
                c11(newSize), c12(newSize), c21(newSize), c22(newSize),
                p1(newSize), p2(newSize), p3(newSize), p4(newSize),
                p5(newSize), p6(newSize), p7(newSize);
        // Ділимо матриці на підматриці
        for (int i = 0; i < newSize; i++) {
            for (int j = 0; j < newSize; j++) {
                a11[i][j] = A[i][j];
                a12[i][j] = A[i][j + newSize];
                a21[i][j] = A[i + newSize][j];
                a22[i][j] = A[i + newSize][j + newSize];
                b11[i][j] = B[i][j];
                b12[i][j] = B[i][j + newSize];
                b21[i][j] = B[i + newSize][j];
                b22[i][j] = B[i + newSize][j + newSize];
            }
        }
        StrassenMultiplication(a11, b12 - b22, p1);
        StrassenMultiplication(a11 + a12, b22, p2);
        StrassenMultiplication(a21 + a22, b11, p3);
        StrassenMultiplication(a22, b21 - b11, p4);
        StrassenMultiplication(a11 + a22, b11 + b22, p5);
        StrassenMultiplication(a12 - a22, b21 + b22, p6);
        StrassenMultiplication(a11 - a21, b11 + b12, p7);
        c11 = p4 + p5 + p6 - p2;
        c12 = p1 + p2;
        c21 = p3 + p4;
        c22 = p1 + p5 - p3 - p7;
        // Складаємо результат у єдину матрицю:
        for (int i = 0; i < newSize; i++) {
            for (int j = 0; j < newSize; j++) {
                Product[i][j] = c11[i][j];
                Product[i][j + newSize] = c12[i][j];
                Product[i + newSize][j] = c21[i][j];
                Product[i + newSize][j + newSize] = c22[i][j];
            }
        }
    }
References ComplexMatrix< T >::columns, ComplexMatrix< T >::rows, and ComplexMatrix< T >::StrassenMultiplication().
Referenced by ComplexMatrix< T >::StrassenMultiplication(), and ComplexMatrix< T >::StrassenMultiply().
StrassenMultiply()
template<typename T > ComplexMatrix< T > ComplexMatrix< T >::StrassenMultiply (ComplexMatrix< T > Matrix) inline
Multiply two matrices using Strassen Multiply O(n^(log2(7))) ~ O(n^2.8074) if n <= 64 O(n^3)
Parameters
Matrix - right matrix
Returns
product
Definition at line 491 of file ComplexMatrix.h.
{
        if (this->columns != Matrix.rows) {
            printError(CANNOT_MULTIPLY_ERROR_CODE);
            return *this;
        }
        // Next power of 2
        int power = max({ this->rows, this->columns, Matrix.columns});
        int size = (int)pow(2, ceil(log2(power)));
        ComplexMatrix<T> AResized(size), BResized(size), Product(size);
        for (int i = 0; i < this->rows; i++) {
            for (int j = 0; j < this->columns; j++) {
                AResized[i][j] = (*this)[i][j];
            }
        }
        for (int i = 0; i < Matrix.rows; i++) {
            for (int j = 0; j < Matrix.columns; j++) {
                BResized[i][j] = Matrix[i][j];
            }
        }
        StrassenMultiplication(AResized, BResized, Product);
        ComplexMatrix Result(this->rows, Matrix.columns);
        for (int i = 0; i < this->rows; i++) {
            for (int j = 0; j < Matrix.columns; j++) {
                Result[i][j] = Product[i][j];
            }
        }
        return Result;
    }
References ComplexMatrix< T >::columns, printError(), ComplexMatrix< T >::rows, and ComplexMatrix< T >::StrassenMultiplication().
Referenced by TEST_CASE(), testMultiplicationErrorDifference(), and testStrassenAlgorithm().
swapColumns()
template<typename T > void ComplexMatrix< T >::swapColumns (const int & firstColumn, const int & secondColumn) inline private
Swaps two columns of a matrix.
Parameters
firstColumn
secondColumn
Definition at line 41 of file ComplexMatrix.h.
{
        for (int i = 0; i < this->rows; i++) {
            Complex<T> columnCopy = this->matrix[i][firstColumn];
            this->matrix[i][firstColumn] = this->matrix[i][secondColumn];
            this->matrix[i][secondColumn] = columnCopy;
        }
    }
References ComplexMatrix< T >::rows.
Referenced by ComplexMatrix< T >::getInverseLU().
swapRows()
template<typename T > void ComplexMatrix< T >::swapRows (const int & firstRow, const int & secondRow) inline private
Swaps two rows of a matrix.
Parameters
firstRow
secondRow
Definition at line 28 of file ComplexMatrix.h.
{
        for (int i = 0; i < this->columns; i++) {
            Complex<T> rowCopy = this->matrix[firstRow][i];
            this->matrix[firstRow][i] = this->matrix[secondRow][i];
            this->matrix[secondRow][i] = rowCopy;
        }
    }
References ComplexMatrix< T >::columns.
Referenced by ComplexMatrix< T >::getInverseGaussJordan(), ComplexMatrix< T >::getInverseLU(), and ComplexMatrix< T >::getLUDecomposition().
Member Data Documentation
columns
template<typename T > unsigned int ComplexMatrix< T >::columns {} private
Definition at line 20 of file ComplexMatrix.h.
Referenced by ComplexMatrix< T >::ComplexMatrix(), ComplexMatrix< T >::ComplexMatrix(), ComplexMatrix< T >::getColumns(), ComplexMatrix< T >::getInverseGaussJordan(), ComplexMatrix< T >::getInverseLU(), ComplexMatrix< T >::getLUDecomposition(), ComplexMatrix< T >::getTransposed(), ComplexMatrix< T >::operator*(), ComplexMatrix< T >::operator+(), ComplexMatrix< T >::operator-(), ComplexMatrix< T >::operator==(), ComplexMatrix< T >::print(), ComplexMatrix< T >::StrassenMultiplication(), ComplexMatrix< T >::StrassenMultiply(), and ComplexMatrix< T >::swapRows().
matrix
template<typename T > vector<vector<Complex<T> > > ComplexMatrix< T >::matrix private
Definition at line 21 of file ComplexMatrix.h.
Referenced by ComplexMatrix< T >::ComplexMatrix(), and ComplexMatrix< T >::ComplexMatrix().
rows
template<typename T > unsigned int ComplexMatrix< T >::rows {} private
Definition at line 19 of file ComplexMatrix.h.
Referenced by ComplexMatrix< T >::ComplexMatrix(), ComplexMatrix< T >::ComplexMatrix(), ComplexMatrix< T >::getInverseGaussJordan(), ComplexMatrix< T >::getInverseLU(), ComplexMatrix< T >::getLUDecomposition(), ComplexMatrix< T >::getRows(), ComplexMatrix< T >::getTransposed(), ComplexMatrix< T >::operator*(), ComplexMatrix< T >::operator+(), ComplexMatrix< T >::operator-(), ComplexMatrix< T >::operator==(), ComplexMatrix< T >::print(), ComplexMatrix< T >::StrassenMultiplication(), ComplexMatrix< T >::StrassenMultiply(), and ComplexMatrix< T >::swapColumns().
The documentation for this class was generated from the following file:
Headers/ComplexMatrix.h